<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Menu_Addon;

class addonseeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $Addon = [
            [
                'addon_id' => 1,
                'menu_id' => 1,
                'addon_name' => 'Telur',
                'menu_category_id' => 3,
                'addon_price' => 0.00,
            ],
            [
                'addon_id' => 2,
                'menu_id' => 1,
                'addon_name' => 'Bakso',
                'menu_category_id' => 3,
                'addon_price' => 0.00,
            ],
            [
                'addon_id' => 3,
                'menu_id' => 1,
                'addon_name' => 'Sosis',
                'menu_category_id' => 3,
                'addon_price' => 0.00,
            ],
            [
                'addon_id' => 4,
                'menu_id' => 1,
                'addon_name' => 'Ayam',
                'menu_category_id' => 3,
                'addon_price' => 0.00,
            ],
            [
                'addon_id' => 5,
                'menu_id' => 1,
                'addon_name' => 'Telur & Ayam',
                'menu_category_id' => 3,
                'addon_price' => 3000.00,
            ],
            [
                'addon_id' => 6,
                'menu_id' => 2,
                'addon_name' => 'Telur',
                'menu_category_id' => 3,
                'addon_price' => 0.00,
            ],
            [
                'addon_id' => 7,
                'menu_id' => 2,
                'addon_name' => 'Bakso',
                'menu_category_id' => 3,
                'addon_price' => 0.00,
            ],
            [
                'addon_id' => 8,
                'menu_id' => 2,
                'addon_name' => 'Sosis',
                'menu_category_id' => 3,
                'addon_price' => 0.00,
            ],
            [
                'addon_id' => 9,
                'menu_id' => 2,
                'addon_name' => 'Ayam',
                'menu_category_id' => 3,
                'addon_price' => 0.00,
            ],
            [
                'addon_id' => 10,
                'menu_id' => 2,
                'addon_name' => 'Telur & Ayam',
                'menu_category_id' => 3,
                'addon_price' => 3000.00,
            ],
            [
                'addon_id' => 11,
                'menu_id' => 3,
                'addon_name' => 'Telur',
                'menu_category_id' => 3,
                'addon_price' => 3000.00,
            ],
            [
                'addon_id' => 12,
                'menu_id' => 3,
                'addon_name' => 'Keju',
                'menu_category_id' => 3,
                'addon_price' => 3000.00,
            ],
            [
                'addon_id' => 13,
                'menu_id' => 3,
                'addon_name' => 'Kornet',
                'menu_category_id' => 3,
                'addon_price' => 4000.00,
            ],
            [
                'addon_id' => 14,
                'menu_id' => 3,
                'addon_name' => 'Spesial (Telur, Kornet, & Keju)',
                'menu_category_id' => 3,
                'addon_price' => 9000.00,
            ],
            [
                'addon_id' => 15,
                'menu_id' => 4,
                'addon_name' => 'Telur',
                'menu_category_id' => 3,
                'addon_price' => 3000.00,
            ],
            [
                'addon_id' => 16,
                'menu_id' => 4,
                'addon_name' => 'Keju',
                'menu_category_id' => 3,
                'addon_price' => 3000.00,
            ],
            [
                'addon_id' => 17,
                'menu_id' => 4,
                'addon_name' => 'Kornet',
                'menu_category_id' => 3,
                'addon_price' => 4000.00,
            ],
            [
                'addon_id' => 18,
                'menu_id' => 4,
                'addon_name' => 'Spesial (Telur, Kornet, & Keju)',
                'menu_category_id' => 3,
                'addon_price' => 9000.00,
            ],
            [
                'addon_id' => 19,
                'menu_id' => 6,
                'addon_name' => 'Kornet',
                'menu_category_id' => 3,
                'addon_price' => 4000.00,
            ],
            [
                'addon_id' => 20,
                'menu_id' => 7,
                'addon_name' => 'Telur',
                'menu_category_id' => 3,
                'addon_price' => 0.00,
            ],
            [
                'addon_id' => 21,
                'menu_id' => 7,
                'addon_name' => 'Kornet',
                'menu_category_id' => 3,
                'addon_price' => 0.00,
            ],
            [
                'addon_id' => 22,
                'menu_id' => 7,
                'addon_name' => 'Keju',
                'menu_category_id' => 3,
                'addon_price' => 0.00,
            ],
            [
                'addon_id' => 23,
                'menu_id' => 7,
                'addon_name' => 'Cokelat',
                'menu_category_id' => 3,
                'addon_price' => 0.00,
            ],
            [
                'addon_id' => 24,
                'menu_id' => 7,
                'addon_name' => 'Kacang',
                'menu_category_id' => 3,
                'addon_price' => 0.00,
            ],
            [
                'addon_id' => 25,
                'menu_id' => 7,
                'addon_name' => 'Nanas',
                'menu_category_id' => 3,
                'addon_price' => 0.00,
            ],
            [
                'addon_id' => 26,
                'menu_id' => 7,
                'addon_name' => 'Strawberry',
                'menu_category_id' => 3,
                'addon_price' => 0.00,
            ],
            [
                'addon_id' => 27,
                'menu_id' => 7,
                'addon_name' => 'Telur & Kornet',
                'menu_category_id' => 3,
                'addon_price' => 3000.00,
            ],
            [
                'addon_id' => 28,
                'menu_id' => 7,
                'addon_name' => 'Telur & Keju',
                'menu_category_id' => 3,
                'addon_price' => 3000.00,
            ],
            [
                'addon_id' => 29,
                'menu_id' => 7,
                'addon_name' => 'Kornet & Keju',
                'menu_category_id' => 3,
                'addon_price' => 3000.00,
            ],
            [
                'addon_id' => 30,
                'menu_id' => 7,
                'addon_name' => 'Cokelat & Keju',
                'menu_category_id' => 3,
                'addon_price' => 3000.00,
            ],
            [
                'addon_id' => 31,
                'menu_id' => 7,
                'addon_name' => 'Kacang & Keju',
                'menu_category_id' => 3,
                'addon_price' => 3000.00,
            ],
            [
                'addon_id' => 32,
                'menu_id' => 7,
                'addon_name' => 'Nanas & Keju',
                'menu_category_id' => 3,
                'addon_price' => 3000.00,
            ],
            [
                'addon_id' => 33,
                'menu_id' => 7,
                'addon_name' => 'Strawberry & Keju',
                'menu_category_id' => 3,
                'addon_price' => 3000.00,
            ],
            [
                'addon_id' => 34,
                'menu_id' => 7,
                'addon_name' => 'Pisang, Keju, & Cokelat',
                'menu_category_id' => 3,
                'addon_price' => 4000.00,
            ],
            [
                'addon_id' => 35,
                'menu_id' => 7,
                'addon_name' => 'Spesial (Telur, Kornet, & Keju)',
                'menu_category_id' => 3,
                'addon_price' => 8000.00,
            ],
            [
                'addon_id' => 36,
                'menu_id' => 12,
                'addon_name' => 'Es',
                'menu_category_id' => 3,
                'addon_price' => 2000.00,
            ],
            [
                'addon_id' => 37,
                'menu_id' => 13,
                'addon_name' => 'Es',
                'menu_category_id' => 3,
                'addon_price' => 2000.00,
            ],
            [
                'addon_id' => 38,
                'menu_id' => 14,
                'addon_name' => 'Es',
                'menu_category_id' => 3,
                'addon_price' => 2000.00,
            ],
            [
                'addon_id' => 39,
                'menu_id' => 15,
                'addon_name' => 'Es',
                'menu_category_id' => 3,
                'addon_price' => 2000.00,
            ],
            [
                'addon_id' => 40,
                'menu_id' => 24,
                'addon_name' => 'Susu',
                'menu_category_id' => 3,
                'addon_price' => 2000.00,
            ],
            [
                'addon_id' => 41,
                'menu_id' => 25,
                'addon_name' => 'Es',
                'menu_category_id' => 3,
                'addon_price' => 1000.00,
            ],
            [
                'addon_id' => 42,
                'menu_id' => 26,
                'addon_name' => 'Es',
                'menu_category_id' => 3,
                'addon_price' => 1000.00,
            ],
            [
                'addon_id' => 43,
                'menu_id' => 27,
                'addon_name' => 'Es',
                'menu_category_id' => 3,
                'addon_price' => 1000.00,
            ],
            [
                'addon_id' => 44,
                'menu_id' => 28,
                'addon_name' => 'Es',
                'menu_category_id' => 3,
                'addon_price' => 1000.00,
            ],
            [
                'addon_id' => 45,
                'menu_id' => 28,
                'addon_name' => 'Susu',
                'menu_category_id' => 3,
                'addon_price' => 2000.00,
            ],
            [
                'addon_id' => 46,
                'menu_id' => 29,
                'addon_name' => 'Es',
                'menu_category_id' => 3,
                'addon_price' => 1000.00,
            ],
            [
                'addon_id' => 47,
                'menu_id' => 29,
                'addon_name' => 'Susu',
                'menu_category_id' => 3,
                'addon_price' => 2000.00,
            ],
            [
                'addon_id' => 48,
                'menu_id' => 30,
                'addon_name' => 'Es',
                'menu_category_id' => 3,
                'addon_price' => 1000.00,
            ],
            [
                'addon_id' => 49,
                'menu_id' => 30,
                'addon_name' => 'Susu',
                'menu_category_id' => 3,
                'addon_price' => 2000.00,
            ],
            [
                'addon_id' => 50,
                'menu_id' => 31,
                'addon_name' => 'Es',
                'menu_category_id' => 3,
                'addon_price' => 1000.00,
            ],
            [
                'addon_id' => 51,
                'menu_id' => 31,
                'addon_name' => 'Susu',
                'menu_category_id' => 3,
                'addon_price' => 2000.00,
            ],
            [
                'addon_id' => 52,
                'menu_id' => 32,
                'addon_name' => 'Es',
                'menu_category_id' => 3,
                'addon_price' => 1000.00,
            ],
            [
                'addon_id' => 53,
                'menu_id' => 33,
                'addon_name' => 'Es',
                'menu_category_id' => 3,
                'addon_price' => 1000.00,
            ],
            [
                'addon_id' => 54,
                'menu_id' => 34,
                'addon_name' => 'Es',
                'menu_category_id' => 3,
                'addon_price' => 2000.00,
            ],
            [
                'addon_id' => 55,
                'menu_id' => 35,
                'addon_name' => 'Es',
                'menu_category_id' => 3,
                'addon_price' => 2000.00,
            ],
            [
                'addon_id' => 56,
                'menu_id' => 36,
                'addon_name' => 'Es',
                'menu_category_id' => 3,
                'addon_price' => 1000.00,
            ],
            [
                'addon_id' => 57,
                'menu_id' => 37,
                'addon_name' => 'Fanta',
                'menu_category_id' => 3,
                'addon_price' => 0.00,
            ],
            [
                'addon_id' => 58,
                'menu_id' => 37,
                'addon_name' => 'Sprite',
                'menu_category_id' => 3,
                'addon_price' => 0.00,
            ],
            [
                'addon_id' => 59,
                'menu_id' => 37,
                'addon_name' => 'Coca-Cola',
                'menu_category_id' => 3,
                'addon_price' => 0.00,
            ],
            [
                'addon_id' => 60,
                'menu_id' => 37,
                'addon_name' => 'Susu',
                'menu_category_id' => 3,
                'addon_price' => 3000.00,
            ],
            [
                'addon_id' => 61,
                'menu_id' => 38,
                'addon_name' => 'Susu',
                'menu_category_id' => 3,
                'addon_price' => 1000.00,
            ],
            [
                'addon_id' => 62,
                'menu_id' => 39,
                'addon_name' => 'Susu',
                'menu_category_id' => 3,
                'addon_price' => 2000.00,
            ],
            [
                'addon_id' => 63,
                'menu_id' => 40,
                'addon_name' => 'Susu',
                'menu_category_id' => 3,
                'addon_price' => 2000.00,
            ],            
        ];        

        foreach ($Addon as $addon) { 
            Menu_addon::create($addon);
        }        
    }
}
